GRAPHQL http://localhost:8080/graphql

mutation {
    addAuthor(input:{ authorName:"우용7" }){
        books{
            id
            publishedDate
            publisher
            title
        }
        id
        name
        reviews{
            id
            rating
            content
            createdDate
        }
    }
}

